name: backend-ci

on:
  pull_request:
    paths:
      - 'src/**'
      - 'pom.xml'
      - '.github/workflows/backend-ci.yml'
      - 'postman/**'
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'pom.xml'
      - '.github/workflows/backend-ci.yml'
      - 'postman/**'

concurrency:
  group: backend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'maven'

      - name: Debug workspace (optional)
        run: |
          pwd
          ls -la

      - name: Build & test
        run: mvn -B clean verify -Dspring.profiles.active=ci

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: |
          if [ -z "${{ secrets.RENDER_DEPLOY_HOOK_URL }}" ]; then
            echo "RENDER_DEPLOY_HOOK_URL is not set; skipping deploy."
            exit 0
          fi
          curl -fsSL -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"