name: backend-ci

on:
  pull_request:
    paths:
      - 'matrix_ads_backend/**'
      - '.github/workflows/backend-ci.yml'
  push:
    branches: [ main ]
    paths:
      - 'matrix_ads_backend/**'
      - '.github/workflows/backend-ci.yml'

concurrency:
  group: backend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: matrix_ads_backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'maven'

      - name: Build & test
        run: mvn -B -DskipTests=false clean verify

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: |
          if [ -z "${{ secrets.RENDER_DEPLOY_HOOK_URL }}" ]; then
            echo "RENDER_DEPLOY_HOOK_URL is not set; skipping deploy."
            exit 0
          fi
          curl -fsSL -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"